### ISSUE TITLE
Named export `set` not found

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#84] opened 2021-11-02 00:51 UTC
See https://github.com/react-hook-form/resolvers/issues/271?fbclid=IwAR1RuwBxUAZVFvgFvqYWtYObDFqXitN_SYBQ4eBecg7iLeT8dagv3nlPmSI

![image](https://user-images.githubusercontent.com/52666982/139769397-6d869e7e-ea9e-4607-99ba-bdbf4c527edb.png)

**Comment by vitokhangnguyen** [comment] 2021-11-02 05:20
Temporarily fixed by importing `yupResolver` from `@hookform/resolvers/yup/dist/yup'  instead of `@hookform/resolvers/yup`

Let's keep this issue open and keep watch on react-hook-form/resolvers#271 to see if the problem is fixed.

**Comment by Andrewnt219** [comment] 2021-11-02 05:52
Why's gray?

**Comment by vitokhangnguyen** [comment] 2021-11-02 07:32
> Why gray?

Keeping this issue open to see if any news from react-hook-form/resolvers#271

**Comment by hongdeyuan** [comment] 2021-11-02 07:44
> Temporarily fixed by importing `yupResolver` from `@hookform/resolvers/yup/dist/yup' instead of `@hookform/resolvers/yup`
> 


This is a way to bypass the Rust compiler and does not solve the fundamental problem. If you install a dependency that does not satisfy the CommonJS module, the project will still not run properly

**Closed** 2021-12-10 04:27 UTC
Labels: type: bug & fix, area: frontend, priority: asap, status: gray
